server:
  port: 8801

spring:
  application:
    name: albrus-cloud-stream-provider  # 服务别名
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      bindings: # 服务的整合处理
        albrusSend-out-0: # 这个名字是一个通道的名称
          destination: studyExchange
          content-type: application/json # 设置消息类型，本次为 json，文本则设置 text/plain
        albrusSend1-out-0: # 这个名字是一个通道的名称
          destination: studyExchange1
          content-type: application/json # 设置消息类型，本次为 json，文本则设置 text/plain
        albrusSend2-out-0: # 这个名字是一个通道的名称
          destination: studyExchange2
          content-type: application/json # 设置消息类型，本次为 json，文本则设置 text/plain
      rabbit:
        bindings:
          albrusSend1-out-0:
            producer:
              autoBindDlq: true # 自动绑定死信队列，会自动创建一个默认的死信队列
    function:
      definition: albrusSend;albrusSend1;albrusSend2

eureka:
  client:
    register-with-eureka: true  # 将自己注册到 EurekaServer
    fetch-registry: true  # 是否从 EurekaServer 抓取已有的注册信息，默认为 true。单节点无所谓，集群必须设置为 true 才能配合 ribbon 使用负载均衡
    service-url:
      # defaultZone: http://localhost:7001/eureka/  # 路径包含 /eureka 是因为 EurekaServer 内部有 web 过滤器
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/  # 集群配置
    registry-fetch-interval-seconds: 30  # 隔多久从服务中心拉取一次服务列表，默认 30s
  instance:
    # 使用 IP 注册，否则会使用主机注册（此处考虑老版本的兼容，新版本经过实验都是 IP）
    prefer-ip-address: true
    # 自定义实例显示格式，加上版本号便于多版本管理，注意是 ip-address，早期版本是 ipaddress
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    # 自定义元数据（key/value 结构）
    metadata-map:
      cluster: cll
      region: rnl
    lease-renewal-interval-in-seconds: 30  # 租约续约间隔时间，默认 30s
    lease-expiration-duration-in-seconds: 90  # 租约到期，服务时效时间，默认值 90s，服务超过 90s 没有发⽣⼼跳，EurekaServer 会将服务从列表移除