server:
  port: 83

spring:
  application:
    name: albrus-cloud-order-service  # 服务别名
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.20.161:8848

service-url: # 消费者将要去访问的微服务名称（注册到 Nacos 的微服务提供者）
  nacos-base-service: http://albrus-cloud-payment-service
  module:
    payment: ${service-url.nacos-base-service}/payment
